version: '3.7'

services:
  backend:
    container_name: CritialDMG-api
    build: 
      context: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - ${API_PORT}:3000
    environment:
      - NODE_ENV=${NODE_ENV}
    links: 
      - database
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=chat

volumes:
  database: